#!/bin/bash
WIDTH=1280
HEIGHT=720
FORMAT=I420

function assert() {
    local message="$1"
    shift
    "$@"
    local rc=$?
    [ $rc -eq 0 ] && return 0
    set $(caller)
    date=$(date "+%Y-%m-%d %T%z")
    echo "$date $2 [$$]: $message (line=$1, rc=$rc)" >&2
    exit $rc
}

# Get the ID_V4L_PRODUCT property of a special file.
function get_id_v4l_product() {
    local special_file="$1"

    udevadm info --query=property "${special_file}" \
        | grep "ID_V4L_PRODUCT" \
        | cut -c 16-
}

# Look for the v4l2loopback /dev/video* file.
function find_v4l2loopback_file() {
    local video_device
    local video_desc

    printf 'Looking for v4l2loopback special file:\n' >&2
    for video_device in /dev/video*
    do
        video_desc="$(get_id_v4l_product "${video_device}" 2>/dev/null)"

        printf '  - %s (%s) -> ' "${video_device}" "${video_desc}" >&2
        if [ "${video_desc}" == "Dummy video device (0x0000)" ]
        then
            printf 'FOUND!\n' >&2
            printf '%s' "${video_device}"
        else
            printf 'not a v4l2loopback special file\n' >&2
        fi
    done
}

assert "v4l2loopback module not loaded" grep -q v4l2loopback /proc/modules
assert "video4linux driver not found" grep -q video4linux /proc/devices
assert "udevadm not found" which udevadm > /dev/null

DUMMY_WEBCAM="$(find_v4l2loopback_file)"
assert "${DUMMY_WEBCAM} does not exist" test -e ${DUMMY_WEBCAM}
assert "${DUMMY_WEBCAM} is not writable" test -w ${DUMMY_WEBCAM}

printf 'Reloading v4l2loopback\n'
assert "Unable to unload v4l2loopback" sudo modprobe --remove v4l2loopback
sudo modprobe v4l2loopback

printf 'Setting up %s to %s pixel format at %d×%d\n' \
    "${DUMMY_WEBCAM}" \
    "${FORMAT}" \
    "${WIDTH}" \
    "${HEIGHT}"

sudo v4l2loopback-ctl \
    set-caps "video/x-raw, format=${FORMAT}, width=${WIDTH}, height=${HEIGHT}" \
    "${DUMMY_WEBCAM}" \
    2>/dev/null >/dev/null \
    && printf 'Done!\n'
