#!/bin/bash
DUMMY_WEBCAM=/dev/video0
VIDEO_WIDTH=1280
VIDEO_HEIGHT=720
IMAGE="$1"

function assert() {
	local message="$1"
	shift
	"$@"
	local rc=$?
	[ $rc -eq 0 ] && return 0
	set $(caller)
	date=$(date "+%Y-%m-%d %T%z")
	echo "$date $2 [$$]: $message (line=$1, rc=$rc)" >&2
	exit $rc
}

assert "v4l2loopback module not loaded" grep -q v4l2loopback /proc/modules
assert "${DUMMY_WEBCAM} does not exist" test -e ${DUMMY_WEBCAM}
assert "${DUMMY_WEBCAM} is not writable" test -w ${DUMMY_WEBCAM}
assert "FFmpeg is not installed" which ffmpeg > /dev/null
assert "'${IMAGE}' not found" test -f "${IMAGE}"
assert "'${IMAGE}' not readable" test -r "${IMAGE}"

scaling="w=${VIDEO_WIDTH}:h=${VIDEO_HEIGHT}:force_original_aspect_ratio=1"
padding="${VIDEO_WIDTH}:${VIDEO_HEIGHT}:(ow-iw)/2:(oh-ih)/2:color=black"
ffmpeg \
    -re \
    -i "${IMAGE}" \
    -vf "format=yuv420p, scale=${scaling}, pad=${padding}" \
    -f v4l2 \
    "${DUMMY_WEBCAM}"

